### ISSUE TITLE
Error refreshing token

### ISSUE THREAD

**Issue by wolfracer** [iterative/PyDrive2#101]
I have a service that runs every 30 minutes, to fetch some data in a google sheet, and modify it in some cases depending on some conditions, every week or every 5 days, the service just stop running, displaying this error.

```python
Traceback (most recent call last):
  File "c:\Users\isabe_000\proyectos_isa\WorkIsa\Parodi\Gdrive_folders\sheet.py", line 94, in <module>
    sheet = Sheet()
  File "c:\Users\isabe_000\proyectos_isa\WorkIsa\Parodi\Gdrive_folders\sheet.py", line 54, in _init_
    self.gc = pygsheets.authorize(client_secret='sheet_secret.json')
  File "C:\Python39\lib\site-packages\pygsheets\authorization.py", line 129, in authorize
    credentials = _get_user_authentication_credentials(client_secret, scopes, credentials_directory, local)
  File "C:\Python39\lib\site-packages\pygsheets\authorization.py", line 40, in _get_user_authentication_credentials
    credentials.refresh(Request())
  File "C:\Python39\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Python39\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Python39\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Python39\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')`
```

https://github.com/Orisoth/Gdrive_folders here is my repo.

the only fix i found, is that i erase the credentials files, and then i redo the auth proccess again.

**Comment by shcheklein** [comment]
@wolfracer could you please check that `get_refresh_token` is set here as described [here](https://github.com/iterative/PyDrive2/issues/92#issuecomment-788213806) and/or [here](https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#automatic-and-custom-authentication-with-settings-yaml).

Looks like `https://github.com/Orisoth/Gdrive_folders` is private?

If `get_refresh_token` please share a bit more information/code - how do you do auth, what do you have in the settings file, etc.

Thanks.

**Comment by wolfracer** [comment]
> @wolfracer could you please check that `get_refresh_token` is set here as described [here](https://github.com/iterative/PyDrive2/issues/92#issuecomment-788213806) and/or [here](https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#automatic-and-custom-authentication-with-settings-yaml).
> 
> Looks like `https://github.com/Orisoth/Gdrive_folders` is private?
> 
> If `get_refresh_token` please share a bit more information/code - how do you do auth, what do you have in the settings file, etc.
> 
> Thanks.
check now, it is public now, yes i got that setting

`client_config_file: sheet_secret.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: cred_token/credential.json
get_refresh_token: True`

**Comment by shcheklein** [comment]
@wolfracer hi, thanks! Please make your project private back (you can invite me as a collaborator) and rotate your keys please, since anyone can access it at the moment.

Also, it looks like `C:\Python39\lib\site-packages\pygsheets\authorization.py` `pygsheets` fails, not `PyDrive2`, so not sure this is a relevant repo to handle this? I would in the `pygsheets`'s repo.

Please, if I'm missing something here, feel free to reopen the issue.

Thanks!

**Comment by leandroSJ** [comment]
A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

**Comment by meet1919** [comment]
Hey, @shcheklein  I am facing the same issue. I didnt found any issue related to `pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.` in `pygsheets`
```
gauth.LoadCredentialsFile("mycreds.txt")
if gauth.credentials is None:
    # Authenticate if they're not there
    gauth.LocalWebserverAuth()
elif gauth.access_token_expired:
    # Refresh them if expired
    gauth.Refresh()
else:
    # Initialize the saved creds
    gauth.Authorize()
# Save the current credentials to a file
gauth.SaveCredentialsFile("mycreds.txt")
```

The seems to work and refresh the token earlier but now it doesnt.  Upon looking to the `auth.py` in `pydrive2` I found this:
```
if self.http is None:
    self.http = self._build_http()
try:
    self.credentials.refresh(self.http)
except AccessTokenRefreshError as error:
    raise RefreshError("Access token refresh failed: %s" % error)
```

The problem seems to arising at `self.credentials.refresh(self.http)`. I dont know what is `self.http` but the problem might be coming from `self._build_http()`. What should I do?

**Comment by mrkprdo** [comment]
Is this already fixed?
