### ISSUE TITLE
problem with InsertPermission() optional parameters: sendNotificationEmails=False is not working

### ISSUE THREAD

**Issue by abubelinha** [iterative/PyDrive2#102]
I am having an issue which did already exist in the original PyDrive project.
A solution was supposed to be already available, but never merged (see [PyDrive issue 95](https://github.com/googleworkspace/PyDrive/issues/95#issuecomment-295659033)):

> Specifying optional parameters is now possible as additional parameters to the InsertPermission() function like so:
> 
> ```
> file1.InsertPermission({'type': 'user',
>                                          'value': 'insert@email.here',
>                                          'role': 'reader'}, sendNotificationEmails=False)
> ```
> 

Could you please incorporate it to PyDrive2 ?
It's pretty annoying receiving so many emails when you are just testing code.

-----
EDIT: in the mean time I keep using the original PyDrive when I have to call the `InsertPermission()` function.
This is what I did to get the patch in Windows 7 ([development branch installed using pips, without git](https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github#comment21549755_15268990)):

`pip install --upgrade https://github.com/googledrive/PyDrive/tarball/development
`

(Note: the current github path for the PyDrive project seems to have moved from `googledrive` to `googleworkspace`, but the above url did still work for me)

**Comment by shcheklein** [comment]
Happy to merge a PR with this changes - https://github.com/googleworkspace/PyDrive/commit/2540716dd309f6db33ccf7d5a26f6b480b299647 . @abubelinha do you want to do a PR?

**Comment by abubelinha** [comment]
Sorry but I have no git/programming skills to do it.  I wish I could.
But actually I always get lost when I try to understand how git works.  

I just found the solution in the old project and I was lucky enough to find a way to install it without using git.

**Comment by shcheklein** [comment]
Hi, @abubelinha I checked it once again and I think it had been fixed a while ago - now you can provide an optional dict like this:

```python
params = {`sendNotificationEmails`: False}
file1.InsertPermission({'type': 'user',
                                         'value': 'insert@email.here',
                                         'role': 'reader'}, params)
```

please, give it a try and let's see if it works

**Comment by abubelinha** [comment]
Thank you @shcheklein and sorry for the delay.
Indeed it works (using normal quotes ... your example params has backtick quotes).

I am just wondering if it also exists a UpdatePermission method (it [exists in Google Drive api](https://developers.google.com/drive/api/v2/reference/permissions/update))

Otherwise, what would be the way to update an extant permission for a given user?
Delete it first (looping all permissions and deleting those belonging to the intended user), and finally Insert the new permission again?

Thanks a lot

**Comment by shcheklein** [comment]
@abubelinha hi! no worries.

Yes, it looks like `UpdatePermission` is not exposed directly in the PyDrive. I think get all, delete, insert is the reasonable workaround. But feel free to create a feature request- we'll take a look.

**Comment by sagarsharma19** [comment]
Hi @shcheklein, @abubelinha  When I am using this code its throwing an error saying : **InsertPermission() takes 2 positional arguments but 3 were given**

Code Snippet : 
params = {'sendNotificationEmail':False}
permission = gfile.InsertPermission({'type': 'user','value': email,'role': 'writer'},params)

Please Help,
Thanks
