### ISSUE TITLE
Memory Usage increasing after download and upload

### ISSUE THREAD

**Issue by MizaGBF** [iterative/PyDrive2#112]
Hi.
For a while now, I noticed my memory usage increasing quite a bit whenever I download or upload a file. The memory also seems to not free itself properly even if I try to force a garbage collection with the `gc` module.
It happens on both windows and linux, on python 3.9.5 (and possibly earlier, I have this issue for months but only narrowed it down by chance yesterday). PyDrive2 version is 1.8.3.

Here's my test code:
```python
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

def auth():
    gauth = GoogleAuth()
    gauth.LoadCredentialsFile("credentials.json")
    if gauth.credentials is None:
        gauth.LocalWebserverAuth()
    elif gauth.access_token_expired:
        gauth.Refresh()
    else:
        gauth.Authorize()
    gauth.SaveCredentialsFile("credentials.json")
    return GoogleDrive(gauth)

def foo1(name, folder, iterations):
    drive = auth()
    file_list = drive.ListFile({'q': "'" + folder + "' in parents and trashed=false"}).GetList()
    for s in file_list:
        if s['title'] == name:
            for i in range(iterations): # loop for testing purpose
                s.GetContentFile(s['title'])
            return

def foo2(target, mime, name, folder, iterations):
    drive = auth()
    for i in range(iterations): # loop for testing purpose
        s = drive.CreateFile({'title':name, 'mimeType':mime, "parents": [{"kind": "drive#file", "id": folder}]})
        s.SetContentFile(target)
        s.Upload()

# note: the test file is around 13MB big
foo1("temp.sql", "test_folder_ID", 10) # replace test_folder_ID with the google drive folder you wanna use
foo2("temp.sql", "application/sql", "temp.sql", "test_folder_ID", 10)
```

I tried to dig around on my own to figure it out if it's truly leaking memory but I'm not knowledgeable enough with Python to figure it out.
Something I did notice, however, is those two functions both generate a ResourceWarning (using `python -Wd -X tracemalloc=30`.

foo1:
```
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=556, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('2a01:cb19:68a:3000:a5b2:d826:6155:8145', 56214, 0, 0), raddr=('2a00:1450:4007:811::200a', 443, 0, 0)>
Object allocated at (most recent call last):
  File "C:\Users\Redacted\Documents\python\g.py", lineno 23
    file_list = drive.ListFile({'q': "'" + folder + "' in parents and trashed=false"}).GetList()
  File "C:\Python3\lib\site-packages\pydrive2\apiattr.py", lineno 166
    for x in self:
  File "C:\Python3\lib\site-packages\pydrive2\apiattr.py", lineno 150
    result = self._GetList()
  File "C:\Python3\lib\site-packages\pydrive2\auth.py", lineno 84
    return decoratee(self, *args, **kwargs)
  File "C:\Python3\lib\site-packages\pydrive2\files.py", lineno 85
    self.auth.service.files()
  File "C:\Python3\lib\site-packages\googleapiclient\_helpers.py", lineno 134
    return wrapped(*args, **kwargs)
  File "C:\Python3\lib\site-packages\googleapiclient\http.py", lineno 920
    resp, content = _retry_request(
  File "C:\Python3\lib\site-packages\googleapiclient\http.py", lineno 191
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Python3\lib\site-packages\oauth2client\transport.py", lineno 173
    resp, content = request(orig_request_method, uri, method, body,
  File "C:\Python3\lib\site-packages\oauth2client\transport.py", lineno 280
    return http_callable(uri, method=method, body=body, headers=headers,
  File "C:\Python3\lib\site-packages\httplib2\__init__.py", lineno 1708
    (response, content) = self._request(
  File "C:\Python3\lib\site-packages\httplib2\__init__.py", lineno 1424
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Python3\lib\site-packages\httplib2\__init__.py", lineno 1346
    conn.connect()
  File "C:\Python3\lib\site-packages\httplib2\__init__.py", lineno 1138
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "C:\Python3\lib\ssl.py", lineno 500
    return self.sslsocket_class._create(
  File "C:\Python3\lib\ssl.py", lineno 1003
    self = cls.__new__(cls, **kwargs)
```
foo2:
```
C:\Users\Redacted\Documents\python\g.py:33: ResourceWarning: unclosed file <_io.BufferedReader name='temp.sql'>
  s = drive.CreateFile({'title':name, 'mimeType':mime, "parents": [{"kind": "drive#file", "id": folder}]})
Object allocated at (most recent call last):
  File "C:\Users\Redacted\Documents\python\g.py", lineno 34
    s.SetContentFile(target)
  File "C:\Python3\lib\site-packages\pydrive2\files.py", lineno 261
    self.content = open(filename, "rb")
```
I don't know if it's related to my memory problem, but that's all I could find.

EDIT: In case this can help, I did some profiling using the [memory-profiler](https://pypi.org/project/memory-profiler/) module, **without the iterations**:
foo1:
```
Filename: g.py
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    17     27.4 MiB     27.4 MiB           1   @profile
    18                                         def foo1(name, folder, iterations):
    19     28.4 MiB      1.0 MiB           1       drive = auth()
    20     31.3 MiB      2.9 MiB           1       file_list = drive.ListFile({'q': "'" + folder + "' in parents and trashed=false"}).GetList()
    21     31.3 MiB      0.0 MiB           3       for s in file_list:
    22     31.3 MiB      0.0 MiB           3           if s['title'] == name:
    23     31.9 MiB      0.6 MiB           1               s.GetContentFile(s['title'])
    24     31.9 MiB      0.0 MiB           1               return
```
foo2:
```
Filename: g.py
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    26     27.4 MiB     27.4 MiB           1   @profile
    27                                         def foo2(target, mime, name, folder, iterations):
    28     28.3 MiB      1.0 MiB           1       drive = auth()
    29     28.3 MiB      0.0 MiB           1       s = drive.CreateFile({'title':name, 'mimeType':mime, "parents": [{"kind": "drive#file", "id": folder}]})
    30     28.3 MiB      0.0 MiB           1       s.SetContentFile(target)
    31     31.1 MiB      2.8 MiB           1       s.Upload()
    32     31.1 MiB      0.0 MiB           1       return True
```

**Comment by shcheklein** [comment]
Yes, it's related (at least one of the problems) to this issue #20 . Take a look here for a workaround (effectively, we use `with` to close this on the client level):

https://github.com/iterative/PyDrive2/blob/master/pydrive2/fs/spec.py#L343-L356

The first warning might be related to the connection pool and the requests library handles this. If you run it in a cycle and keep creating auth, drive objects again and and again, do you see sockets leaking?

>  The memory also seems to not free itself properly even if I try to force a garbage collection with the gc module.

Overall this is a tricky one. How do you determine the memory footprint. I'm not 100% sure but `gc` frees memory in the heap, but I don't it (always) frees/shrinks the process memory that is allocated for the heap.

**Comment by MizaGBF** [comment]
For context, I use pydrive2 to remotely store the persistent data from my Discord Bot, which runs all the time, and that's how I noticed the memory usage building up (going as far as 400MB, as opposed to the usual 80MB, when doing a lot of upload/download).  
It has been a while, here's what I remember trying:
- Keeping one auth instance alive, instead of creating multiples, didn't seem to affect the issue in any way, the memory kept building up  
- However, looking at my old code, I don't think I tried keeping one Drive instance, and kept creating a new one when needed instead. Do you think I should give it a try?
- On my bot, I used psutil to measure the memory usage, using the `rss` value from `memory_info()`. I remember trying other things, such as checking `gc.get_objects` and `gc.get_stats`, but I forgot if their output were normal or not. Then again, memory and such in python isn't really my field of expertise., I'm not sure if I can help you more on that side.  
  
I'll check out the workaround your mentionned as soon as I have some time, along with the sockets. For now, I was simply using pydrive2 in a separate process using `multiprocessing`. Quite overkill but it solved all my memories issues.

**Comment by MizaGBF** [comment]
I did some upload test directly on my Discord Bot (it was the easiest thing for me, at the moment), here's some results.
First, for good measure, I updated to pydrive 1.9.1 and tested my old code by looping 1000 uploads:
- `ResourceWarning: unclosed file` still happen
- The memory still increases

Next, I tested your workaround (replacing `s.SetContentFile()` by an `with open` statement followed by `s.content = stream`):
- No more Resource Warnings, as expected
- The memory seems stable but I'll let it run more to be sure.

I'll keep you updated and try to check the unclosed socket warning as soon as I can.

**Comment by MizaGBF** [comment]
> I did some upload test directly on my Discord Bot (it was the easiest thing for me, at the moment), here's some results.
> First, for good measure, I updated to pydrive 1.9.1 and tested my old code by looping 1000 uploads:
> 
> * `ResourceWarning: unclosed file` still happen
> * The memory still increases
> 
> Next, I tested your workaround (replacing `s.SetContentFile()` by an `with open` statement followed by `s.content = stream`):
> 
> * No more Resource Warnings, as expected
> * The memory seems stable but I'll let it run more to be sure.
> 
> I'll keep you updated and try to check the unclosed socket warning as soon as I can.

Small update for the above:
1. The memory still increased by around 50 MB in total, after the 1000 uploads. I still think the workaround helped, however, as it's way less than the increases I used to notice in the past.
2. I got a ResourceWarning unclosed socket when closing the application: `sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('REDACTED', 60554), raddr=('74.125.193.95', 443)>`
For reference, my test code was pretty much the same as `foo2` in my first post, with the workaround mentionned earlier.
I grabbed the socket list just after the test, if it can help:
```
[
sconn(fd=10, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='REDACTED', port=60554), raddr=addr(ip='74.125.193.95', port=443), status='CLOSE_WAIT', pid=4), 
sconn(fd=3, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='REDACTED', port=58616), raddr=addr(ip='74.125.193.95', port=443), status='CLOSE_WAIT', pid=4),
sconn(fd=4, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='REDACTED', port=58628), raddr=addr(ip='74.125.193.95', port=443), status='ESTABLISHED', pid=4),
sconn(fd=7, family=<AddressFamily.AF_UNIX: 1>, type=<SocketKind.SOCK_STREAM: 1>, laddr='', raddr='', status='NONE', pid=4),
sconn(fd=6, family=<AddressFamily.AF_UNIX: 1>, type=<SocketKind.SOCK_STREAM: 1>, laddr='', raddr='', status='NONE', pid=4)
]```

**Comment by MizaGBF** [comment]
Sorry for the wait, I ended up a bit busy.  
I did more testing like promised with some slight modifications of my test code following your suggestions:  
1. I kept one drive instance during the test duration.  
2. I changed `SetContentFile()` by an `with` statement.  
  
The Pydrive2 version used is `1.9.2` and the Python version is `3.9.1`.  
```python
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
import gc
from memory_profiler import profile

drive = None

@profile
def auth():
    global drive
    if drive is None:
        gauth = GoogleAuth()
        gauth.LoadCredentialsFile("credentials.json")
        if gauth.credentials is None:
            gauth.LocalWebserverAuth()
        elif gauth.access_token_expired:
            gauth.Refresh()
        else:
            gauth.Authorize()
        gauth.SaveCredentialsFile("credentials.json")
        drive = GoogleDrive(gauth)
    return drive

@profile
def foo1(name, folder):
    file_list = drive.ListFile({'q': "'" + folder + "' in parents and trashed=false"}).GetList()
    for s in file_list:
        if s['title'] == name:
            s.GetContentFile(s['title'])
            return

@profile
def foo2(target, mime, name, folder):
    s = drive.CreateFile({'title':name, 'mimeType':mime, "parents": [{"kind": "drive#file", "id": folder}]})
    with open(target, "rb") as stream:
        s.content = stream
        s.Upload()

auth()
for i in range(0, 20):
    foo1("test.sql", "redacted_folder_id")
    foo2("test.sql", "application/sql", "temp.sql", "redacted_folder_id")
```  
I joined the profiling result in `test1.txt`.  
[test1.txt](https://github.com/iterative/PyDrive2/files/7121723/test1.txt)  
If I'm understanding it right, there is a memory increase of 0.4 MiB on average per `Upload()` and `GetContentFile()` calls.  
I'm ignoring the `ListFile().GetList()` increase as, I assume, it's related to the number of file present in my test folder, which is growing during the test.  
  
Next, I tried adding a `gc.collect()` call to see how it would react.  
```python
@profile()
def gctest():
    gc.collect()
```  
called in the loop after the `foo2()` call.  
It does free around 1.0 MiB of memory per call but, again, it might be related to `ListFile().GetList()` and the end still results in a memory increase (From 28.5 MiB before the first `foo1` call to `31.6 MiB` at the very end), although a small one.  
The details are in `test2.txt`.  
[test2.txt](https://github.com/iterative/PyDrive2/files/7121724/test2.txt)  
  
Finally I tried to look for any unclosed sockets.  
The only one staying up during the whole thing is this one:  
`[pconn(fd=-1, family=<AddressFamily.AF_INET6: 23>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='redacted', port=60751), raddr=addr(ip='2a00:1450:4007:80c::200a', port=443), status='ESTABLISHED')]`.  
It only appears after the first iteration, so it's not generated by the `auth()` call.  
  
That's all for now. I hope it was helpful in some way.

**Comment by shcheklein** [comment]
So, these numbers are still too small to say anything. Python engine (CPython?) allocates memory from OS in chunks and then it's being used to put objects. Running GC frees space in these chunks but I doubt it'll return chunks back to OS (probably there are some thresholds, etc). 

We actually need to use tools `get_objects` and/or something like this https://stackoverflow.com/questions/552744/how-do-i-profile-memory-usage-in-python 

Alternatively, we can let it run a very long cycle and see if it's stable. If it leaks memory it'll crash eventually.

What is your concern with it taking 30MiB?

**Comment by MizaGBF** [comment]
In short, in one of my long running application, I end up with huge memory usage (~400 MB) after a few hours of letting it run, which ended making it crash if I let it run too long. Like I mentionned previously, I now do all my drive related stuff in a separate process to be sure the memory is free, which is a bit bothersome.  
I agree 30MiB is small, and some of it is certainly allocated by the memory profiler module, maybe my test is flawed.  
I could try to let it run longer and try get_objects if you want. Like I said, I'm no expert at memory profiling and stuff in python  so I'm a bit clueless at what's the best approach is to make a better diagnosis of my issue.

**Comment by MizaGBF** [comment]
Long time no see.  
I started working on another project using pydrive2, not so long ago, and I believe the issue to be fixed. At the very least, memory doesn't seem to be building up overtime anymore.  
For reference sake, I tested on both Python 3.10.7 and 3.11.0, on Ubuntu and Windows, with Pydrive2 1.14.0 and 1.15.0.  

My pydrive2 code hasn't changed much (beside the fact I switched to a Service Account) but it's possible something I did in the past year fixed it. I was quarantining the code in a separate process to ensure the memory not building up over long periods of time, on my previous project, so I was quite blind to any changes related on this issue.  
However, I did notice some odd behaviors while trying to understand if it was truly gone, so I came back to report them, in the case that it might be important.    

First, according to the docstring of `SetContentFile()`, `Upload()` is supposed to close the file set in the content attribute of a `GoogleDriveFile` object. However, I'm not seeing the close call anywhere.  
I ended up testing the following:  
```python
s = drive.CreateFile({'title':'test.json', 'mimeType':'text/JSON', "parents": [{"kind": "drive#file", "id": folder}]})
stream = io.BytesIO()
stream.write(data.encode('utf-8'))
s.content = stream
s.Upload()
s.content.getbuffer()
```  
and the `getbuffer()` call doesn't cause an "operation on closed file" exception.  
As such, I believe the file opened in [SetContentFile](https://github.com/iterative/PyDrive2/blob/main/pydrive2/files.py#L259) might not get closed properly either.  
If I'm not wrong, you might want to look into all the cases where content is set with an BytesIO buffer or file. I took notes of those other three:  
* The [two BytesIO objects created by FetchContent](https://github.com/iterative/PyDrive2/blob/main/pydrive2/files.py#L479).  
* The [BytesIO object created by SetContentString](https://github.com/iterative/PyDrive2/blob/main/pydrive2/files.py#L245)  
  
Going further, I also noticed, [in MediaIoReadable __init__()](https://github.com/iterative/PyDrive2/blob/main/pydrive2/files.py#L143), a BytesIO object which doesn't seem to be closed either.  

This is all I could find.  
I'm pretty sure I wasn't not calling any of those pieces of code or I was properly closing/cleaning up, after implementing the [workarounds your suggested last year](https://github.com/iterative/PyDrive2/issues/112#issuecomment-901455739), so I can't say with certainty one of those was the cause of my headache.  

Regardless, I'll keep monitoring my new App for any weird memory increase but feel free to close this issue as you see fit.
