### ISSUE TITLE
Building your own authentication flow - How to with Flask?

### ISSUE THREAD

**Issue by stock90975** [iterative/PyDrive2#114]
Hi,

I'm trying to get PyDrive2 to work on my website (not localhost) 

I've got [settings.yaml](https://iterative.github.io/PyDrive2/docs/build/html/oauth.html?highlight=settings%20yaml#sample-settings-yaml) working for localhost

```python
from pydrive2.auth import GoogleAuth

gauth = GoogleAuth(settings_file='settings.yaml')
gauth.LocalWebserverAuth()
```
which saves credentials to `credentials.json`
So, `settings.yaml` & my GCP Authorized redirect URIs (http://localhost:8080/) work

I've read [Building your own authentication flow](https://iterative.github.io/PyDrive2/docs/build/html/oauth.html?highlight=settings%20yaml#building-your-own-authentication-flow) but I don't understand how to implement it in Flask, especially:

```python
auth_url = gauth.GetAuthUrl() # Create authentication url user needs to visit
code = AskUserToVisitLinkAndGiveCode(auth_url) # Your customized authentication flow
```

Can anyone show me some **Flask code**, and related **Redriect URIs** to achieve this?

Thanks very much!

**Comment by shcheklein** [comment]
I would try to authorize `your-app.com/callback` URL and use code would ty to direct users to the `AuthUrl`. After they approve it should automatically redirect it back to your app.

**Comment by shinz4u** [comment]
@shcheklein  Could you please explain it a bit more with code snippets please?

**Comment by shcheklein** [comment]
I think this is related https://docs.iterative.ai/PyDrive2/oauth/#building-your-own-authentication-flow and can help.
