### ISSUE TITLE
Authenticate pydrive2 with stored credentials in server/ database

### ISSUE THREAD

**Issue by shinz4u** [iterative/PyDrive2#118]
As currently `file` is the only possible place to save the credentials. I am unable to use pydrive in my server side application. 

I am storing the credentials ( access_token, refresh tokens and the rest) in db so that I can use them again to re authenticate PyDrive for those particular users without asking them to do the auth flow again. 

I was wondering is there is a way I can authorize PyDrive with stored credentials? I would like to `LoadCredentials()` from the DB

Is there a workaround for this that I can implement? 
          
          from pydrive2.auth import GoogleAuth
          gauth = GoogleAuth(settings_file="pydrive_settings.yaml")
          # At this point gauth.credentials will be None

I would like to run `LoadCredentials()` with the stored values in DB but, `LoadCredentials()` work with `Storage`. So looking for a workaround here.

Can I call the refresh token directly to google and then assign it to pydrive? or get the code from google auth again and use  `gauth.Auth(code)` or something?

**Comment by shcheklein** [comment]
Related https://github.com/iterative/PyDrive2/issues/115

@shinz4u I don't know an easy solution for this unfortunately. Would be glad to give some feedback/help/guidance if someone could try to add this.

**Comment by shinz4u** [comment]
@shcheklein I have a PR here which worked well for my purpose, Let me know if this will work. I am not sure of the security implications. So do suggests changes. 

https://github.com/iterative/PyDrive2/pull/124

**Comment by shcheklein** [comment]
You can now pass a dict like object via `GoogleAuth(settings={...})` that also includes a dict with credentials:

https://github.com/iterative/PyDrive2/blob/main/pydrive2/fs/spec.py#L86-L90

Internal logic will be triggering updates to this dict that could be intercepted and database call can be issued. 

This should be enough to cover the DB scenario.
