### ISSUE TITLE
ci: exceeding rate limits when running in parallel

### ISSUE THREAD

**Issue by efiop** [iterative/PyDrive2#122]
See https://github.com/iterative/PyDrive2/pull/121#issuecomment-894528154

**Comment by shcheklein** [comment]
I think we are in a decent shape now, @efiop ?

**Comment by efiop** [comment]
@shcheklein I guess :man_shrugging: But it would be nice for our code to maybe retry a bit more or something. But that's a topic for another time, good enough for now. :+1:
