### ISSUE TITLE
Uploading in parts

### ISSUE THREAD

**Issue by TejasDhanda-L11** [iterative/PyDrive2#130]
How could I upload file in form of different parts, as they are being downloaded.

I am downloading a file's parts using multi-threading so speed it up.
I want to upload those parts to gdrive using generators, as they are being downloaded (present in ram), how could I achieve that in PyDrive2?

**Comment by shcheklein** [comment]
@TejasDhanda-L11 I think the best way in this case would to use GDrive API directly - https://developers.google.com/drive/api/v3/manage-uploads#http---multiple-requests

**Comment by TejasDhanda-L11** [comment]
@shcheklein 
Thanks bro for the reply, I will try to make direct api work, but I am new bee in it, hope I will be able to make it work.
