### ISSUE TITLE
How to choose a parent directory when uploading a file ?

### ISSUE THREAD

**Issue by tristanlatr** [iterative/PyDrive2#131]
Hi,

How to choose a parent directory when uploading a file ?

I don't see any example that details this use case in the docs.

I just want a simple script to upload a file to a specific directory. 

Thanks for your answer.

**Comment by tristanlatr** [comment]
By choosing I mean just giving it's ID or something, not selecting with the web browser.

**Comment by shcheklein** [comment]
hi @tristanlatr ! It looks like this (don't pay attention to `stream` here, `parent_id` is the what you need):

```python
    def gdrive_upload_fobj(self, title, parent_id, stream, callback=None):
        item = self.client.CreateFile(
            {"title": title, "parents": [{"id": parent_id}]}
        )
        item.content = stream
        item.Upload()
        return item
```
