### ISSUE TITLE
KeyError when calling LoadCredentialsFile()

### ISSUE THREAD

**Issue by tristanlatr** [iterative/PyDrive2#132]
Hi, I'm running into a key error when loading credentials from a json file. I suspect this might be a bug. 

```python
File "/usr/local/lib/python3.9/site-packages/pydrive2/auth.py", line 348, in LoadCredentialsFile
    self.credentials = storage.get()
  File "/usr/local/lib/python3.9/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/local/lib/python3.9/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/local/lib/python3.9/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

Here is my code
```python
#!/usr/bin/env python3

from typing import IO
import pydrive2.auth
import pydrive2.drive
import fire

def gdrive_upload_fobj(drive: pydrive2.drive.GoogleDrive, title: str, parent_id: str, stream: IO):
        
        item = drive.CreateFile(
            {"title": title, "parents": [{"id": parent_id}]}
        )
        item.content = stream
        item.Upload()
        return item

def upload(file: str = '', folder: str = '', creds: str = '') -> None:
    """
    Uploads a file to google drive folder, given a file name and the folder ID.
    """
    if not file or not folder:
        raise RuntimeError("You must provide arguments --file and --folder")

    auth = pydrive2.auth.GoogleAuth()
    auth.LoadCredentialsFile(creds or 'credentials.json')
    drive = pydrive2.drive.GoogleDrive(auth)

    with open(file, 'rb') as fileob:

        gdrive_upload_fobj(drive, fileob.name, parent_id=folder, stream=fileob)

if __name__ == "__main__":
    fire.Fire(upload)
```

**Comment by shcheklein** [comment]
Most likely something is wrong with the credentials file. Do you by chance pass the same `credentials.json` to the `LoadCredentialsFile` that you got from the Google cloud console?

Also, do you have a custom `settings.yaml` or do you rely on defaults?

**Comment by tristanlatr** [comment]
>  Do you by chance pass the same credentials.json to the LoadCredentialsFile that you got from the Google cloud console?

This is exactly what I did. 

> do you have a custom settings.yaml or do you rely on defaults? 

No I don't

**Comment by shcheklein** [comment]
> This is exactly what I did.

Yep, I know this is confusing, but `LoadCredentialsFile` expects a different file. And usually you don't even have to provide it. Auth flow creates it for you, save it, updates it when it's needed etc.

Here is the excerpt from the docs:

> OAuth is complicated and it requires a lot of settings. By default, when you don’t provide any settings, PyDrive will automatically set default values which works for most of the cases. Here are some default settings.

> Read client configuration from file client_secrets.json
> OAuth scope: https://www.googleapis.com/auth/drive
> Don’t save credentials
> Don’t retrieve refresh token

By default, I think it expects you to name the file you got from Google as `client_secrets.json`, then create a file `settings.yaml` with the following structure.

https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#sample-settings-yaml

```yaml
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
```

I know it's complicated. To summarize there are three files (and some of them are optional based on the settings):

`settings.yaml` - defines general behavior, name can be customized if needed
`client_secrets.json` - this one you get from Google (it has different types depending on you using service accounts, etc). It has application credentials.
`credentials.json` - will be a file that defines _your_ personal credentials that are needed to access data on _your_ behalf.

All this things can be changed and modified if it's necessary.

I would recommend reading the full doc here: https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#oauth-made-easy
