### ISSUE TITLE
No quota when uploading file to shared drive

### ISSUE THREAD

**Issue by paulgavrikov** [iterative/PyDrive2#142]
I'd like to upload a file to a shared drive (public link and anyone with the link can edit). My personal drive is full, the shared drive has lots of storage left and enough to store the file. 
However, when I attempt to upload my file I get the following error: `ResumableUploadError: <HttpError 403 when requesting None returned "The user has exceeded their Drive storage quota". Details: "[{'domain': 'usageLimits', 'reason': 'quotaExceeded', 'message': 'The user has exceeded their Drive storage quota'}]">`

Which I suspect means that I am not correctly uploading the file to the shared drive. 

Here's my code - is any attribute set incorrectly?

```python
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

gauth = GoogleAuth()
gauth.CommandLineAuth()

drive = GoogleDrive(gauth)

file_path = "myfile.csv"
file = drive.CreateFile({'parents': [{"kind": "drive#fileLink", 'id': "XXXXXXXXXXXXXXXXXXXXX"}]})
file.SetContentFile(file_path)
file.Upload(param={'supportsAllDrives': True, 'enforceSingleParent': True})
```

I am using PyDrive2 1.9.4.

**Comment by shcheklein** [comment]
Have tried to run it w/o `"kind": "drive#fileLink"`? Also, I assume the `id` is the shared drive `id` in this case, could you confirm?

**Comment by paulgavrikov** [comment]
@shcheklein thanks for the response. I have and still get the error but removing the `SetContentFile` call creates the file in the shared drive.

**Comment by shcheklein** [comment]
@paulgavrikov `call creates the file in the shared drive.` - an empty one?

could you try something like:

```python
file = drive.CreateFile({'title': 'test', 'parents': [{'id': "XXXXXXXXXXXXXXXXXXXXX"}]})
with open("myfile.csv", "rb") as stream:
   file.content = stream
   file.Upload()
```

I don't this we need anything else here. It should be working like this.

**Comment by paulgavrikov** [comment]
@shcheklein 

> call creates the file in the shared drive. - an empty one?
yes, an empty file (which probably fits in my quota).

I tried the snippet you sent and I still run into the same error.

**Comment by shcheklein** [comment]
could you please give me a full script (Github gist) that reproduces this? I'll try to run it.

**Comment by paulgavrikov** [comment]
@shcheklein Ivan, I just checked and I run into the same issue if I upload the file manually via the Drive UI. Uploading to public drives counts against the uploader's quota, not the quota of the provider. So this is not a PyDrive2 issue. 

Thanks for your time!
