### ISSUE TITLE
Can't sign in on Google Colab

### ISSUE THREAD

**Issue by Raychanan** [iterative/PyDrive2#151]
Hi, many thanks for developing this package! I have some difficulties using PyDrive on Google Colab. 

Colab Notebook: https://colab.research.google.com/drive/1bkDcXa0Yf96-0hZeQrGjsbdgmPNhNXSt?usp=sharing

Reproduce:

1. Download and rename credential file as suggested on https://docs.iterative.ai/PyDrive2/quickstart/
![image](https://user-images.githubusercontent.com/53246211/141715440-3678fb5a-2e82-4efd-828b-806480b71d40.png)

2. Create settings.yaml 

```yaml
client_config_backend: settings
client_config:
  client_id: ----
  client_secret: -----
```

3. Upload settings.yaml to Colab 
4. Run the code chunk 

```python
from pydrive2.auth import GoogleAuth

gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Creates local webserver and auto handles authentication.
```

Finally, an error pops up.
![image](https://user-images.githubusercontent.com/53246211/141715666-0d1a32c1-9e41-4901-b863-cc16dadeace5.png)

However, adding `http://localhost:8080/` `http://localhost:8090/` to Authorized redirect URIs, and adding `http://localhost:8080` `http://localhost:8090` don't help solve the issue.

![image](https://user-images.githubusercontent.com/53246211/141716173-f7abed51-ede7-4a33-b4c4-6c296c10dea2.png)

Many thanks for help!

**Comment by shcheklein** [comment]
Hi @Raychanan . In your case I see that redirect URI has port 8090, but you authorized 8080. I think that should be the main problem?

**Comment by shcheklein** [comment]
Have you tried to check this https://stackoverflow.com/questions/65756266/error-403-access-denied-the-developer-hasn-t-given-you-access-to-this-app-despi ?

And overall the consent screen?

It might you are hitting some limits for an unverified app? Overall we need more details, script to reproduce, could you share a Colab project we can easily run to experiment with?
