### ISSUE TITLE
Module not found error: No module named 'pydrive2' yet it is installed

### ISSUE THREAD

**Issue by StuartNeoW** [iterative/PyDrive2#155]
Subject of the issue
I installed pydrive2 but not able to import the module in anaconda environment.

I tried
conda install -c conda-forge pydrive2
pip install pydrive2
pip install git+https://github.com/iterative/PyDrive2.git#egg=PyDrive2

And later I opened Pycharm as well as Jupyter Notebook in Anaconda Navigator with code like

from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()

However, it returns the error

ModuleNotFoundError: No module named 'pydrive2'

I tried pip3 freeze and able to see pydrive2 there
PyDrive==1.3.1 (I previously also installed PyDrive)
PyDrive2 @ file:///home/conda/feedstock_root/build_artifacts/pydrive2_1632348934831/work

How should I make it work? Many thanks!

**Comment by efiop** [comment]
Cannot reproduce. There is something wrong with your environment. From looking at your message, I see that you've installed pydrive using both conda, pip and pip3, and it looks like you are mixing those up which is causing the confusion.
