### ISSUE TITLE
Can we use existing credentials instead of having to explicitly log through the browser?

### ISSUE THREAD

**Issue by greghor** [iterative/PyDrive2#162]
Hi and thanks for the awesome lib. 

I using pydrive2 to upload a pandas dataframe to a gdrive. 

The dataframe is first obtained as the output of a dbt model. Since dbt also requires authentication, I was wondering if it is possible to reuse the corresponding credentials without having to log in again when pydrive2 is called.

I have the feeling that this can be handled in the `settings.yml` file but I didn't find a proper way to do it so far. Every pointer is very welcome.

**Comment by vtasca** [comment]
Hi @greghor, I'm not sure about dbt authentication but you can definitely automate logging into Drive using pydrive2, by specifying a couple of options in `settings.yml`. Actually [this SO answer](https://stackoverflow.com/a/48312989/7878991) explains it really well.

**Comment by abubelinha** [comment]
See also [googlearchive/Pydrive#108](https://github.com/gsuitedevs/PyDrive/issues/108) (related issue in the original PyDrive project, about `oauth_scope` in your settings file)

@abubelinha
