### ISSUE TITLE
Token Refresh With Unpublished App

### ISSUE THREAD

**Issue by jneilliii** [iterative/PyDrive2#171]
> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

Does anyone know of a way to get around this with some other method of OAuth or setting? I've written two plugins for another application (OctoPrint) that implements it's own custom auth flow due to its web server not typically being publicly available. 

https://github.com/jneilliii/OctoPrint-GoogleDriveFiles/blob/a15f29cb6c22a49a23e0185afe5237051c263716/octoprint_googledrivefiles/__init__.py#L280

Any help/suggestions would be greatly appreciated.

**Comment by shcheklein** [comment]
Closing as as stale
