### ISSUE TITLE
Merge PRs from PyDrive

### ISSUE THREAD

**Issue by efiop** [iterative/PyDrive2#2]
E.g. https://github.com/iterative/dvc/pull/3161#discussion_r367000911

**Comment by shcheklein** [comment]
can we close this?

**Comment by efiop** [comment]
@shcheklein We didn't merge all of them yet.

**Comment by shcheklein** [comment]
@efiop is there a list of PRs we want to merge?

**Comment by efiop** [comment]
@skshetry Need to pick and choose, I don't have any specific list right now.

**Comment by shcheklein** [comment]
@efiop so, is the idea to go through all existing PRs? (from all contributors?)

**Comment by efiop** [comment]
@shcheklein All unmerged ones at least.

**Comment by shcheklein** [comment]
@efiop will take a look if some of them are useful

**Comment by shcheklein** [comment]
Merged https://github.com/gsuitedevs/PyDrive/pull/185 and https://github.com/gsuitedevs/PyDrive/pull/184 (direct into master since it's an obvious change)

**Comment by shcheklein** [comment]
Have checked all PRs - most of them are merged (as well as we fixed a lot of stuff from the active forks) - created separate tickets for those that are not merged - they are not ready, need tests, some of them depend on each other, etc. Might fix some of those when I have time or we can wait for contributors to come to us - we'll be way more responsive. Closing this generic ticket for now.
