### ISSUE TITLE
File not found in delete permissions

### ISSUE THREAD

**Issue by lappazos** [iterative/PyDrive2#220]
https://stackoverflow.com/questions/60888471/inserting-permissions-to-google-drive-file-using-pydrive

**Comment by shcheklein** [comment]
@lappazos looks like it was related to the `supportsTeamDrives` value. PyDrive2 already has it:

```python
# Teamdrive support
param["supportsAllDrives"] = True
```

so, I think that issue should be solved. 

Please add more details if you still experience it.
