### ISSUE TITLE
Upload binary data directly from memory

### ISSUE THREAD

**Issue by covalschi** [iterative/PyDrive2#224]
Hello everyone, 
I have a feature request. 

Can we have a method for GoogleDriveFile to SetContent directly from memory? 
I have a ton of files on remote servers I have to download from there and upload to google drive, but I don't want to save them to disk just to be read to memory right after.  

Thanks for keeping the project alive!

**Comment by shcheklein** [comment]
@covalschi how about `SetContentString`? Also, you can do something similar to its implementation:

```python
        self.content = io.BytesIO(content.encode(encoding))
        if self.get("mimeType") is None:
            self["mimeType"] = "text/plain"
```

e.g:

`file.content = io.BytesIO( )`

It means that you could pass any file-like object, stream to it.

**Comment by covalschi** [comment]
Of course I've tried that, but the problem is with encode(encoding) part - some files just can't be utf-8 encoded.

**Comment by shcheklein** [comment]
so, you could pass any bytes stream to it ... `file.content = ...` (no need to use `SetContentString`). Up to you which encoding to use. By default it's utf-8 / text. But even `SetContentString` can be adjusted, you could pass `encoding` if you want.

**Comment by covalschi** [comment]
> no need to use SetContentString

Ah, never thought about it, thank you!
