### ISSUE TITLE
How to move files and folders accross the drive?

### ISSUE THREAD

**Issue by meet1919** [iterative/PyDrive2#227]
How to change the parent of a file or folder to change to another folder? So I think this way a file/folder can be moved.

**Comment by shcheklein** [comment]
Hey, please check this PR by @simone-viozzi that attempts to implement `mv`. Idea is that you could update files's parent directly and then `Upload` it.

https://github.com/iterative/PyDrive2/pull/217/files

**Comment by shcheklein** [comment]
I would use the `file.Upload()` call though, no the private `file._...`
