### ISSUE TITLE
The user has exceeded their Drive storage quota

### ISSUE THREAD

**Issue by meet1919** [iterative/PyDrive2#238]
I am using service account for automating drive uploads. Earlier so many files were getting uploaded in the daily basis and eveything worked but now I am seeing this error.

```
pydrive2.files.ApiRequestError: <HttpError 403 when requesting None returned "The user has exceeded their Drive storage quota". Details: "[{'domain': 'usageLimits', 'reason': 'quotaExceeded', 'message': 'The user has exceeded their Drive storage quota'}]">
```

Does each individual user who has access to the same account have their respective quota of storage? Currently, the file which is uploaded via `PyDrive2` are owned by the service account (in the file details it shows that they are created by the service account). In the drive currently, only 400kb is used and all the 15GB is free. What is the reason for this error?

Also when deleting any file or folder from the drive UI (which has been uploaded/created by the service account) gets deleted permanently rather than moving to trash/bin.

**Comment by shcheklein** [comment]
hey @meet1919 , it might the same issue as described here https://github.com/iterative/dvc.org/issues/3963 . Service accounts (unless delegation is enabled) have indeed their own (default?) limits.

> Also when deleting any file or folder from the drive UI (which has been uploaded/created by the service account) gets deleted permanently rather than moving to trash/bin.

probably the same reason. They are moved to the service accounts trash? (i'm not 100% sure).

**Comment by meet1919** [comment]
@shcheklein  is there any work around for this? I mean without using delegations?

**Comment by meet1919** [comment]
@shcheklein  Hey, is it possible to transfer/change ownership (to the user whose drive the service account is using) automatically when a file is uploaded from the service account?

**Comment by meet1919** [comment]
I tried this:

```python
file1 = drive.CreateFile({'id': 'id of the file whose owner is service account'})
file1.Upload()

# Insert the permission.
permission = file1.InsertPermission({
                        'type': 'user',
                        'value': 'email of the drive owner',
                        'role': 'owner',
                        'id': 'permission id of the above email'})

print(file1['alternateLink']) 
```

I got an error : 
```
pydrive2.files.ApiRequestError: <HttpError 403 when requesting 
https://www.googleapis.com/drive/v2/files/1Q0WBmLyoGuBbwbfy-9Mdj6OH_c_05n4_/permissions?
supportsAllDrives=true&alt=json returned "Consent is required to transfer ownership of a file to another user.". Details: "
[{'message': 'Consent is required to transfer ownership of a file to another user.', 'domain': 'global', 'reason': 
'consentRequiredForOwnershipTransfer'}]">
```

where do I give this consent?

**Comment by simone-viozzi** [comment]
If you try to change owner using the UI, it will send a mail to the new owner asking to accept the ownership of the file.
![image](https://user-images.githubusercontent.com/19674168/200168136-3d6c6587-2243-492f-a8e4-60a37f4ae0d3.png)
![image](https://user-images.githubusercontent.com/19674168/200168215-24f8e2b9-fda2-42d4-971f-e97a3db54755.png)

I suppose the error is related to this.


If you find a way to transfer ownership bypassing the email confirmation via API, please let me know!

**Comment by meet1919** [comment]
> hey @meet1919 , it might the same issue as described here [iterative/dvc.org#3963](https://github.com/iterative/dvc.org/issues/3963) . Service accounts (unless delegation is enabled) have indeed their own (default?) limits.
> 
> > Also when deleting any file or folder from the drive UI (which has been uploaded/created by the service account) gets deleted permanently rather than moving to trash/bin.
> 
> probably the same reason. They are moved to the service accounts trash? (i'm not 100% sure).

@shcheklein I created a google workspace/admin account and authorized the service account to impersonate a user. I used that service account to upload file to the drive of that user but still the drive uploads to the storage space of the service account rather than the storage space for the user. As described here [iterative/dvc.org#3963](https://github.com/iterative/dvc.org/issues/3963)

> Google service accounts have upload/download limits (which are quite low - at least by standard). If these limits are exceeded pushing/pulling experiments to the remote throws a 403 http error 'The user has exceeded their Drive storage quota'. This issue can be fixed with [delegation](https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority) and setting gdrive_service_account_user_email to be the user email (not service account email) as proposed by @shcheklein.

What is this: `gdrive_service_account_user_email` and where should I configure it in `PyDrive2`

**Comment by meet1919** [comment]
This problem is solved. If service account is used in a Google workspace account than this is how service account can impersonate the gsuite user account.
```python
from pydrive2.auth import GoogleAuth
from oauth2client.service_account import ServiceAccountCredentials

scope = ["https://www.googleapis.com/auth/drive"]
gauth = GoogleAuth()
gauth.auth_method = 'service'
gauth.credentials = ServiceAccountCredentials.from_json_keyfile_name('client_secrets_service.json', scope).create_delegated('xyz@yourdomain')
```
