### ISSUE TITLE
How to redefine settings.yaml path?

### ISSUE THREAD

**Issue by danil-smirnov** [iterative/PyDrive2#25]
Hi,

I wonder is there any way to redefine `settings.yaml` file location?

As in AWS Chalice framework I can't have it in the working directory...

I have tried to call `pydrive.settings.LoadSettingsFile()` method directly before `GoogleAuth()` but it does not seem working...

Any help appreciated!

**Comment by maxhora** [comment]
@danil-smirnov `GoogleAuth` itself should be able to accept custom path to `settings_file` https://github.com/iterative/PyDrive2/blob/master/pydrive2/auth.py#L177

**Comment by danil-smirnov** [comment]
@maxhora Works like a charm! Thank you!
