### ISSUE TITLE
Upload of semi-large file not working

### ISSUE THREAD

**Issue by candlelightner** [iterative/PyDrive2#260]
I have a semi-large file that I want to upload (~200 MB). However, the file is simply not uploaded by my code, even though the upload speed of my instance is around 300Mb/s, so the task should be done rather quickly. There is no error-output or anything alike and the only other two issues that were semi-related were #49 and #98. Am I doing something wrong or do I have to specify some flags that are not mentioned in the documentation?

Thanks.

**Comment by shcheklein** [comment]
No, no special flags are required. ~200MB doesn't sound like a very large file either. 

Could you share your code? What behavior do you see? Does it just hang, does it fail? 

Could you also check that the latest version of the library is installed please.

**Comment by candlelightner** [comment]
Okay, I believe that there were some persistence issues with pip, as changing to another VM without pydrive installed and directly installing pydrive2 worked for me. However, I also changed the file size to under 100 MB (but still over 1 MB, so if I understood correctly, it should still be split?), so that might also be the fix. Anyhow, I will try again with a larger file size as soon as I have time.

My code is basically straight from the examples, except that I am using console login.

**Comment by shcheklein** [comment]
> ... if I understood correctly, it should still be split?

You mean internally, in the upload function? Yes, I think so.

> Anyhow, I will try again with a larger file size as soon as I have time.

Thanks. Let's reopen it the issue persists.
