### ISSUE TITLE
Can this package do non-interactive authentication?

### ISSUE THREAD

**Issue by quantitative-technologies** [iterative/PyDrive2#263]
The `R` package [googledrive](https://googledrive.tidyverse.org/) can do [non-interactive authentication](https://cran.r-project.org/web/packages/gargle/vignettes/non-interactive-auth.html), with multiple supported methods.

Once setup, I have access programmatically without any user interaction needed.

Does PyDrive2 support this?

**Comment by shcheklein** [comment]
@quantitative-technologies there are a few ways to do non-interactive auth in this case.

1. Use service accounts https://github.com/iterative/PyDrive2/issues/21
2. Do interactive auth locally once, get the credentials files that is created and move it to the machine where you run you application. It can be moved as a file, or passed directly as a `json` string or `dict` into `GAuth`.

We don't support yet things like `Workload Identity on Google Kubernetes Engine (GKE)`.
