### ISSUE TITLE
Error 400 : "Corpus and corpora are mutually exclusive options."

### ISSUE THREAD

**Issue by Datavoore** [iterative/PyDrive2#4]
Hello, 

I'm trying to the list of the files/folders of a team shared drive. I have seen posts where people do this with the following lines of code : 
```
file_list = drive.ListFile({ 'q': "'<drive_id>' in parents and trashed=false",
'corpora': "teamDrive",
'teamDriveId': "<drive_id>",
'includeTeamDriveItems': "true",
'supportsTeamDrives': "true"
}).GetList()
```

However when I try to use this code, I get a 400 error with the following message : 

`HttpError 400 when requesting https://www.googleapis.com/drive/v2/files?q=%<drive_id>%27+in+parents+and+trashed%3Dfalse&corpora=teamDrive&teamDriveId=<drive_id>&includeTeamDriveItems=true&supportsTeamDrives=true&maxResults=1000&corpus=DEFAULT&alt=json returned "Corpus and corpora are mutually exclusive options."`

I tried passing the corpus : "None" or None in the param dictionnary but it is always coming back in the request url. Is it due to a change of behavior from the part of google or can it be solved by using the library ?

**Comment by shcheklein** [comment]
hi! @Datavoore . I think it will be fixed by this PR https://github.com/iterative/PyDrive2/pull/6 (that is merged already). And we will try to release a new version soon.

**Comment by Datavoore** [comment]
Thanks, I will keep you updated as soon as the new version comes out.

**Comment by shcheklein** [comment]
@Datavoore I think the new 1.4.2 version is released, could you give it a try, please?

**Comment by Datavoore** [comment]
It is working for me ! Thanks a lot
