### ISSUE TITLE
Resumable upload?

### ISSUE THREAD

**Issue by yohplala** [iterative/PyDrive2#45]
Hi there!

I just discovered PyDrive2 and am very interested in using it.
I was about to see how implementing a python script to upload/list/download files from Google Drive storage and your library appears the way to go.

I read (maybe too quickly) the doc, and also looked for tickets in your GitHub repo with the word 'resumable', and could not find any hint about this.

Please, does PyDrive support 'resumable upload' as described in Google Drive API doc:
https://developers.google.com/drive/api/v3/manage-uploads#resumable

My intent is to upload large files, and it is advised that for files above 5MB, resumable uploads ought to be used.
I was thus about to follow python script shared here for managing resumable upload in python:
https://tanaikech.github.io/2020/03/05/simple-script-of-resumable-upload-with-google-drive-api-for-python/

If supported, how is it triggered?
Thanks for your feedback.
Bests,

**Comment by shcheklein** [comment]
@yohplala PyDrive relies on the [MediaIoBaseUpload](https://googleapis.github.io/google-api-python-client/docs/epy/googleapiclient.http.MediaIoBaseUpload-class.html) and uses `resumable=True` flag internally. So, regular files `Upload` method is already safe and resumable and should handle large files.

**Comment by shcheklein** [comment]
Closing this for now, feel free to reopen and/or follow up with questions.
