### ISSUE TITLE
Creating folder in Google Drive to which uploading files?

### ISSUE THREAD

**Issue by yohplala** [iterative/PyDrive2#46]
Hi,

Reading through the doc, I didn't spot the detail of how creating a folder in GDrive with PyDrive2, and then uploading a file to this folder, still with PyDrive2.
Please, is this possible?

Thanks for your help.
Bests,

**Comment by shcheklein** [comment]
@yohplala check it here - https://github.com/iterative/dvc/blob/0fb9870de66b410e565c682a9802ea5dc64053dc/dvc/remote/gdrive.py#L455

you can then get `item["id"]` and use it in the code similar to this:

https://github.com/iterative/dvc/blob/0fb9870de66b410e565c682a9802ea5dc64053dc/dvc/remote/gdrive.py#L349

**Comment by shcheklein** [comment]
Closing for now, please feel free to follow up with questions!
