### ISSUE TITLE
can't follow steps to obtain oauth credentials

### ISSUE THREAD

**Issue by rick0403** [iterative/PyDrive2#47]
I used PyDrive about 8 months ago to create a basic script to move files to (my) Google Drive and obtain the file ids, which I needed for another application. Very basic. It all worked fine. Revisited today and it is failing because, I believe, I was inactive for too long and the refresh token was deactivated (getting an "invalid grant" response). Seems I need to start over and get new credentials? Now, I have found my way to PyDrive2, thrilled to find it is evolving and actively maintained, but its seems the Google API process has evolved and screens have changed significantly, so the original PyDrive Quickstart guide that walks one through the steps to re-obtain credentials is no longer something I can follow.  Can you advise? Thank you

**Comment by shcheklein** [comment]
@rick0403 usually auth process creates a json file with credentials, can you try to delete (backup) it to start over?

**Comment by rick0403** [comment]
Ivan thanks for the response.  Yes that is exactly what I am trying to do: obtain a new json file with the new credentials.  The problem is, I don't know quite what to do on the Google API console side to do that simple thing.  The old QuickStart guide was really a click-by-click for dummies.  Now I'm getting screens and messages I didn't get a year ago following the old instructions, and I don't know how to respond and I can't get to the point "download your json file".  I could send specific screenshots and questions if that would help (by the end of which, it would be quite easy to rework the old guide).

**Comment by shcheklein** [comment]
@rick0403 so, there are two json files - first one (that you have to go and download) can be obtained like described here https://dvc.org/doc/user-guide/setup-google-drive-remote#using-a-custom-google-cloud-project-recommended , second one that your application generates contains actual auth credentials. I was asking you to try to delete (backup) the second one. The first one does not expire usually. Btw, could you share a link to the instruction you mentioned?

**Comment by rick0403** [comment]
Thank you. Here's the link: https://pythonhosted.org/PyDrive/quickstart.html
I'll try these steps. Thanks for your help!

**Comment by shcheklein** [comment]
@rick0403 closing this ticket for now, but please feel free to follow up in case you have any other questions!
