### ISSUE TITLE
videoMediaMetadata not appearing for some videos.

### ISSUE THREAD

**Issue by Eleiber** [iterative/PyDrive2#52]
Hello, I am trying to make a script to get the VideoMediaMetadata (specifically the resolution) for several videos I have in a shared TeamDrive where I am admin. All videos were added at the same time to the TeamDrive and they are in the same folder, for some reason when I try to access the metadata of the videos after I fetched it through: 
```python
files = drive.ListFile({'fields':'items(id,title,videoMediaMetadata)','q': f"'{folder['id']}' in parents and mimeType != 'application/vnd.google-apps.folder' and trashed=false"}).GetList()
for file in files:
    fileMeta = drive.CreateFile({'id': file['id']})
    fileMeta.FetchMetadata(fields='videoMediaMetadata')
```
It returns me the videoMediaMetadata only for some of the videos in the folder, while in other files the videoMediaMetadata doesn't appear. I already verified and there are only videos in the folder, and all of them have .mkv format.

**Comment by shcheklein** [comment]
Hi! Could you try to run same queries (and play with different parameters like `supportsAllDrives`,  `corpora`) in the online sandbox here? Just to see first if it's related to the PyDrive2 implementation or something else weird is happening here.

**Comment by Eleiber** [comment]
Hello, thanks for your answer! I tried several tests using "Files: get" function in the [API Explorer](https://developers.google.com/drive/api/v2/reference/files/get?apix=true) of Google Drive API, and it gave me the same results than PyDrive, no videoMediaMetadata in some videos, but in others yes, so it looks more of a bug or something with my files. I searched for the following fields `videoMediaMetadata,title,fileExtension` but it just returned me the results I would expect, but without videoMediaMetadata:
```javascript
{
 "title": "MyVideo01.mkv",
 "fileExtension": "mkv"
}
```

**Comment by Eleiber** [comment]
After trying a lot, I discovered the problem was that Drive didn't have the metadata because it wasn't processing the videos, until I opened them manually in my browser and then the metadata appeared. This is the short solution for this, but isn't there a way to force Drive to process the videos automatically with the API? Because it works fine if you have a few files, but if you have a lot of videos that weren't processed, opening them manually would be hard.

**Comment by shcheklein** [comment]
I think you could try to use `Upload` call to update metadata for all your files?

**Comment by Eleiber** [comment]
I already tried using .Upload() before
```python
fileMeta = drive.CreateFile({'id': id})
fileMeta.Upload()
fileMeta.FetchMetadata(fields='videoMediaMetadata')
```
And after the `FetchMetadata` call
```python
fileMeta = drive.CreateFile({'id': id})
fileMeta.FetchMetadata(fields='videoMediaMetadata')
fileMeta.Upload()
```
But none of them are returning the videoMediaMetadata for those files that weren't processed.

**Comment by shcheklein** [comment]
What I mean is something like:

`fileMeta.Upload(params={'videoMediaMetadata': 'video/mp4'})`

(I have no idea about the exact syntax or which field should be updated - I would check the API docs for this and would try to use playground first)

**Comment by shcheklein** [comment]
Closing as stale. Looks like not an issue with PyDrive itself.
