### ISSUE TITLE
Folder Creation 

### ISSUE THREAD

**Issue by BraisedShortRib** [iterative/PyDrive2#55]
Hello,

Is there a feature for creating a folder on google drive in PyDrive2? I know it's in the Google Drive API, as seen [here](https://developers.google.com/drive/api/v3/folder).  I'd like to use it for a personal tool. If it doesn't exist, can I implement it?

**Comment by shcheklein** [comment]
@BraisedShortRib yes, it is possible, see an example here please - https://github.com/iterative/dvc/blob/5d1c1c418c75677379108980970c6546fba8fe18/dvc/tree/gdrive.py#L463-L469

**Comment by shcheklein** [comment]
@BraisedShortRib please, let me know if you need any help using it.

**Comment by BraisedShortRib** [comment]
I got it working. Thank you for the help!

**Comment by abubelinha** [comment]
One question about the provided example:

```Python
    def _gdrive_create_dir(self, parent_id, title):
        parent = {"id": parent_id}
        item = self._drive.CreateFile(
            {"title": title, "parents": [parent], "mimeType": FOLDER_MIME_TYPE}
        )
        item.Upload()
        return item
```
It works perfectly.
If "title" matches the name of a folder which already exists in that "path" (same parent), then no new folder is created.
That makes sense and it is what I would prefer in practice. 

But in theory, Gdrive allows to create different folders with the same name and the same parent.
I tried it from web interface and it works.
I wonder if it's possible to do the same with PyDrive2 
(although I can't figure out anyone, there might be use cases where that is needed)
