### ISSUE TITLE
tests: No such file or directory: 'your-file-path.p12'

### ISSUE THREAD

**Issue by efiop** [iterative/PyDrive2#57]
https://travis-ci.com/github/iterative/PyDrive2/jobs/384960566

**Comment by shcheklein** [comment]
Some glitch? This error happens if env secrets are not properly set- have no idea what caused it in this case, but I can't reproduce it on master. Also, it looks like it happened only on a single machine. Probably we can just skip it for now, @efiop , WDYT?

**Comment by shcheklein** [comment]
Closing as stale.
