### ISSUE TITLE
Setting can only view and prohibit download

### ISSUE THREAD

**Issue by hgalytoby** [iterative/PyDrive2#61]
I have a batch of files<br>
I know how to query files<br>
```python
drive.ListFile({'q': "'id' in parents and trashed=false"}).GetList()
```
Now I want to batch files<br>
Setting can only view and prohibit download<br>
But i don't know how to achieve

**Comment by shcheklein** [comment]
@hgalytoby sorry, but it's not clear what do you want to achieve. Please clarify it, show example, etc, etc.

**Comment by hgalytoby** [comment]
I have many files<br>

Viewer and commenters can see the option to download, print, and copy (activated))<br>

I hope to be able to use the API<br>

All files Viewer and commenters can see the option to download, print, and copy (deactivate)<br>

![image](https://i.imgur.com/CI6rBAd.png)<br>

**Comment by shcheklein** [comment]
Closing as stale
