### ISSUE TITLE
asking for PyDrive2 capabilites for imports automation

### ISSUE THREAD

**Issue by knowledgeorange** [iterative/PyDrive2#63]
Hello, 
First of all I wanted to thank you for creating and maintaining this project, its very useful.
I'm working on a project which there some actions that I want to do with python in drive but I'm not sure if this module is capable of doing. I searched in the whole page, and I found some answers, but not to everything, so I'm looking for your help.

my plan:
1 - I get a bunch of google drive links, which are sharing links for files in other accounts - for example:
https://drive.google.com/open?id=0B-...
first I'd like to know if I can import the files and folders in the links to my drive (and if I have the permissions to do so).
If I can, i'd like to do that.
2 - after I imported the folders and files, I'd like to list them by hierarchy, so I can later connect (by parent id or something) between the files and sub-folders to their parents, until reaching the root drive folder. 
I know I can get the name and id of the files, but I want to keep hierarchy and also other property - the file/.folder size.
3 - I'd like to create for each imported file/folder a sharing link, which can be used by me and others to import it to their drive, or to download it (without the option of editing it).

I guess that all of these is possible in the original API, but its more complicated and if its possible here I'd like to know,
and also about other possible errors that I may be get in my program (in the importing or sharing parts probably).
Thaks alot!

**Comment by shcheklein** [comment]
Closing as stale
