### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by karelin** [iterative/PyDrive2#65]
The links to original docs, both https://gsuitedevs.github.io/PyDrive/docs/build/html/index.html and https://googledrive.github.io/PyDrive/docs/build/html/index.html (new one from PyDrive official repo) are not available (404 error is returned).

**Comment by shcheklein** [comment]
@karelin I've updated the links and the docs. Please take a look - https://iterative.github.io/PyDrive2/docs/build/html/index.html
