### ISSUE TITLE
Cancel download function

### ISSUE THREAD

**Issue by hgalytoby** [iterative/PyDrive2#67]
![image](https://i.imgur.com/h0UtGSk.jpg)<br>
I did not find in the official documentation.<br>
Function circled in the figure.<br>
Does pydrive2 have this function now?<br>

**Comment by shcheklein** [comment]
@hgalytoby it's not clear what function do you expect, to be honest. could you clarify how would it look like, give an example?

**Comment by hgalytoby** [comment]
> @hgalytoby it's not clear what function do you expect, to be honest. could you clarify how would it look like, give an example?

Google Drive uploads file.<br>
Default.<br>
![image](https://i.imgur.com/EZeSGnX.png)<br>

<br><br><br>
I hope to achieve through function.
This.
![image](https://i.imgur.com/h0UtGSk.jpg)<br>

**Comment by hgalytoby** [comment]
> @hgalytoby it's not clear what function do you expect, to be honest. could you clarify how would it look like, give an example?
@shcheklein <br>
Google Drive uploads file.<br>
Default.<br>
![image](https://i.imgur.com/EZeSGnX.png)<br>

<br><br><br>
I hope to achieve through function.
This.
![image](https://i.imgur.com/h0UtGSk.jpg)<br>

**Comment by hgalytoby** [comment]
> @hgalytoby it's not clear what function do you expect, to be honest. could you clarify how would it look like, give an example?

@shcheklein <br><br>

Google Drive uploads file.<br>
Default.<br>
![image](https://i.imgur.com/EZeSGnX.png)<br>

<br><br><br>
I hope to achieve through function.
This.
![image](https://i.imgur.com/h0UtGSk.jpg)<br>

**Comment by shcheklein** [comment]
Sorry, I still can't understand the question/feature request. Please feel free to reopen but clarify what behavior, what function are you looking for.
