### ISSUE TITLE
How set copyRequiresWriterPermission=True?

### ISSUE THREAD

**Issue by hgalytoby** [iterative/PyDrive2#68]
```py
files= drive.ListFile({'q': "'1LbBwK2RoFRH5m5hx8W7qfZ_TSDMwT2U_' in parents and trashed=false"}).GetList()
for file in files:
　　file.??
```
I want to all files in the folder. <br>
Set copyRequiresWriterPermission=True <br>
How to do it?<br>

**Comment by shcheklein** [comment]
@hgalytoby would something like this work for you - https://iterative.github.io/PyDrive2/docs/build/html/filemanagement.html#update-file-metadata ?

**Comment by hgalytoby** [comment]
It worked , thanks <br>
I love you<br>
