### ISSUE TITLE
pydriver2 issue 

### ISSUE THREAD

**Issue by 4oklkilla** [iterative/PyDrive2#75]
Hey guys, I am new to this library and after some hours trying to even run this basic code, I give up. Please, if you know the problem, let me know. 

```python
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()

drive = GoogleDrive(gauth)
```

And the error is :

```
Traceback (most recent call last):
  File "Gdrive.py", line 5, in <module>
    gauth.LocalWebserverAuth()
  File "/home/pi/.local/lib/python3.7/site-packages/pydrive/auth.py", line 125, in _decorated
    self.Auth(code)
  File "/home/pi/.local/lib/python3.7/site-packages/pydrive/auth.py", line 496, in Auth
    self.Authorize()
  File "/home/pi/.local/lib/python3.7/site-packages/pydrive/auth.py", line 523, in Authorize
    self.service = build('drive', 'v2', http=self.http)
  File "/home/pi/.local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/googleapiclient/discovery.py", line 288, in build
    adc_key_path=adc_key_path,
  File "/home/pi/.local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/googleapiclient/discovery.py", line 466, in build_from_document
    if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'
```

Thank you for any help.

**Comment by shcheklein** [comment]
@4oklkilla could you run `pip freeze` please?

**Comment by 4oklkilla** [comment]
`arandr==0.1.9
asn1crypto==0.24.0
automationhat==0.2.0
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
cachetools==3.1.1
Cap1xxx==0.1.3
certifi==2018.8.24
cffi==1.14.4
chardet==3.0.4
Click==7.0
colorama==0.3.7
colorzero==1.1
configparser==3.5.0b2
cookies==2.2.1
cryptography==3.3.1
drumhat==0.1.0
entrypoints==0.3
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
funcsigs==1.0.2
futures==3.3.0
google-api-core==1.24.1
google-api-python-client==1.12.8
google-auth==1.24.0
google-auth-httplib2==0.0.4
googleapis-common-protos==1.52.0
gpiozero==1.5.1
gyp==0.1
httplib2==0.18.1
idna==2.6
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==17.1.1
keyrings.alt==3.1.1
MarkupSafe==1.1.0
mcpi==0.1.1
microdotphat==0.2.1
mock==2.0.0
mote==0.0.4
motephat==0.0.3
numpy==1.16.2
oauth2client==4.1.3
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
pbr==4.2.0
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.5
pigpio==1.44
Pillow==5.4.1
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycparser==2.20
pycrypto==2.6.1
PyDrive==1.3.1
PyDrive2==1.7.1
pyflakes==2.0.0
pygame==1.9.4.post1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pyOpenSSL==20.0.1
pyserial==3.4
pytz==2020.5
pyxdg==0.25
PyYAML==5.3.1
rainbowhat==0.1.0
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
RPi.GPIO==0.7.0
rsa==4.5
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
simplejson==3.16.0
six==1.15.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.4
touchphat==0.0.1
twython==3.7.0
unicornhathd==0.0.4
uritemplate==3.0.1
urllib3==1.24.1
Werkzeug==0.14.1
`

Here it is!

**Comment by shcheklein** [comment]
ah, I see what is the problem here, you should be doing:

```python
from pydrive2.auth import GoogleAuth
...
```
(mind the `pydrive2` not `pydrive`)

And you don't need PyDrive to be installed at all. Actually it's old and potentially if install both it can lead to some dependency conflicts. Please, give it a try, feel free to reopen this issue, if it's still doesn't work.

**Comment by 4oklkilla** [comment]
Thanks man, i did have the pydrive lib installed, so I think, that was a problem too.
