### ISSUE TITLE
Unable to authenticate following documentation instructions

### ISSUE THREAD

**Issue by NakedKoala** [iterative/PyDrive2#77]
I followed all of this:

Go to APIs Console and make your own project.

Search for ‘Google Drive API’, select the entry, and click ‘Enable’.

Select ‘Credentials’ from the left menu, click ‘Create Credentials’, select ‘OAuth client ID’.

Now, the product name and consent screen need to be set -> click ‘Configure consent screen’ and follow the instructions. Once finished:

Select ‘Application type’ to be Web application.

Enter an appropriate name.

Input http://localhost:8080/ for ‘Authorized redirect URIs’.

Click ‘Create’.

Credential set up as instruceted.

<img width="606" alt="Screen Shot 2021-01-27 at 3 52 52 PM" src="https://user-images.githubusercontent.com/14815380/106052574-b9f42900-60b7-11eb-8e04-5be8008fa7f9.png">

Then calling this:

```
from pydrive2.auth import GoogleAuth

gauth = GoogleAuth()
# Create local webserver and auto handles authentication.
gauth.LocalWebserverAuth()

```

Produces a URL
```
http://localhost:8080/?code=4/0AY0e-g6Kb25Ny1axE1CV21UlS_EoP7xaMFC4R9SMcGM48R81Ui4jgvUIX5gJhITufVSYbg&scope=https://www.googleapis.com/auth/drive
```

Which lead to 5 screens below before error out
<img width="632" alt="Screen Shot 2021-01-27 at 3 52 28 PM" src="https://user-images.githubusercontent.com/14815380/106052743-f2940280-60b7-11eb-9748-bad3593e9a62.png">

<img width="844" alt="Screen Shot 2021-01-27 at 3 52 33 PM" src="https://user-images.githubusercontent.com/14815380/106052761-fa53a700-60b7-11eb-83a1-07b88518c005.png">

<img width="666" alt="Screen Shot 2021-01-27 at 3 52 38 PM" src="https://user-images.githubusercontent.com/14815380/106052776-00498800-60b8-11eb-89e2-36551304e00c.png">

<img width="1042" alt="Screen Shot 2021-01-27 at 3 55 13 PM" src="https://user-images.githubusercontent.com/14815380/106052824-0dff0d80-60b8-11eb-8cc5-3b71475d91f2.png">

Final url is this 

```
http://localhost:8080/?code=4/0AY0e-g6Kb25Ny1axE1CV21UlS_EoP7xaMFC4R9SMcGM48R81Ui4jgvUIX5gJhITufVSYbg&scope=https://www.googleapis.com/auth/drive
```

**Comment by mozboz** [comment]
@NakedKoala Seems very strange as the code listening on localhost:8080 clearly worked for the first URL to work. Are you sure the python doesn't crash or you're not stopping it in between clicking the first link and trying the final URL?

What happens to the python script that gives you the first URL? It should just sit there waiting?

If it is sitting there waiting, did you try popping that final URL in e.g. curl or wget or something, just in case your browser is having some problem with non-https URL's or something like that?

**Comment by shcheklein** [comment]
closing since there is no response. @NakedKoala please feel free to reopen it if you have more info to share!

thanks @mozboz for taking a look 🙏
