### ISSUE TITLE
Is it possible to use getpermissions with a teamdrive folder?

### ISSUE THREAD

**Issue by musicalmarc** [iterative/PyDrive2#78]
Hi,

I can list the folders in a team drive using

```python
file_list = drive.ListFile({'q': "mimeType='application/vnd.google-apps.folder' and trashed=false",
                            'teamDriveId': '12345',
                            'supportsAllDrives': True,
                            'corpora': 'drive',
                            'includeItemsFromAllDrives': True
                            }).GetList()
```

It returns a list of folders.  If I then try `folder.GetPermissions()`, it returns `None` for all of them. I've checked the folders and I'm at least 'content creator' on most of them and can see other user's access.

Thanks, Marc.

**Comment by shcheklein** [comment]
@musicalmarc could you share your code to request permissions? Also, have you tried to run it for the regular personal folder (not from the team drive)?

**Comment by musicalmarc** [comment]
Hi it's works with a personal folder but not with a shared folder.  I tested with a shared folder that I have manager access to.

# test shared drive
file_list = drive.ListFile({'q': "mimeType='application/vnd.google-apps.folder' and trashed=false",
                            'teamDriveId': '123456',
                            'supportsAllDrives': True,
                            'corpora': 'drive',
                            'includeItemsFromAllDrives': True
                            }).GetList()

# test personal folder
# file_list = drive.ListFile({
#     'q': "mimeType='application/vnd.google-apps.folder' and trashed=false and '45678' in parents"
#                             }).GetList()

for file1 in file_list:
    print('title: %s, id: %s, permissions: %s' % (file1['title'], file1['id'], file1.GetPermissions()))

--------------------------------
Authentication successful.
title: test2, id: 1_123456, permissions: None
title: test, id: abcdef, permissions: None

**Comment by shcheklein** [comment]
I'm trying to fix it here - #79

**Comment by shcheklein** [comment]
@musicalmarc could you please give it a try https://github.com/iterative/PyDrive2/pull/79 ? you could install from a branch with pip.

**Comment by musicalmarc** [comment]
Hi,  it works perfectly.  Thanks so much, I learned a lot from this.

**Comment by shcheklein** [comment]
@musicalmarc I've release the 1.7.2, please give it a try.
