### ISSUE TITLE
Is there a way to run code without constantly re-authenticating my account? 

### ISSUE THREAD

**Issue by heysmileyface** [iterative/PyDrive2#82]
cant i do this?

**Comment by hagemouse** [comment]
gauth = GoogleAuth()
    gauth.LoadCredentialsFile("mycreds.txt")
    if gauth.credentials is None:
        gauth.LocalWebserverAuth()
    elif gauth.access_token_expired:
        try:
            gauth.Refresh()
        except Exception as e:
            gauth.Authorize()
    else:
        gauth.Authorize()

    gauth.SaveCredentialsFile("mycreds.txt")
    drive = GoogleDrive(gauth)

**Comment by shcheklein** [comment]
@heysmileyface I would recommend taking a look here https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#automatic-and-custom-authentication-with-settings-yaml

and probably you can see some example here as well- https://github.com/iterative/PyDrive2/blob/master/pydrive2/test/test_oauth.py

@hagemouse PyDrive takes care of refreshing the token, unless something is wrong you don't need to refresh ti manually. It also can save credentials for you.

**Comment by thangisme** [comment]
@shcheklein Can you please do a simple example? I tried above code by @hagemouse, but it threw errors. I can't understand the docs enough to get it running
