### ISSUE TITLE
refresh_token retrieved despite setting to False

### ISSUE THREAD

**Issue by leiyiz** [iterative/PyDrive2#87]
initially `get_refresh_token` is set to `True`, then I wanted to require the user to authenticate every 1 hour and changed it to `False`. But after I deleted the original token downloaded and re-authed it, the token saved still has `"refresh_token"` field and the token refreshed with a new `token_expiry` after I tried to send a request again after an hour.

I suspect #72 might be due to a similar issue.

**Comment by leiyiz** [comment]
Upon further investigation, it seems like the only place where `get_refresh_token` is used is here:

https://github.com/iterative/PyDrive2/blob/bf8b9d51033f2bfd8c391f4f6cdffc0969493e39/pydrive2/auth.py#L554-L557

but when I called `gauth.LocalWebserverAuth()` the state right before this line has `self.flow.params` including `{'access_type': 'offline', 'response_type': 'code'}` I don't know enough about how flow is initialized to debug this issue yet. So any help is appreciated

**Comment by leiyiz** [comment]
So I don't know what's the best practice but seems like when the Flow is initialized in `GetFlow()` the default value for `access_type` is `offline`. So I added a line
```
             "access_type": "online",
```
after line 544 and seems like problem fixed.

**Comment by shcheklein** [comment]
@leiyiz it is indeed looks like a bug here - https://github.com/googleapis/oauth2client/pull/572/files - hard to tell why they decided to put `offline` as a default value. 

let me do a bit of research, but your fix might the way to go indeed. Thanks, @leiyiz !

**Comment by shcheklein** [comment]
Should be closed by #88
