### ISSUE TITLE
Is there anyway to pass in an already-parsed token when creating the GoogleAuth object

### ISSUE THREAD

**Issue by leiyiz** [iterative/PyDrive2#90]
We want to read token file by ourselves and pass the map to PyDrive2 `GoogleAuth()`, is there anyway to do that?

**Comment by shcheklein** [comment]
@leiyiz do you mean those tokens you would usually provide via this YAML file - https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#automatic-and-custom-authentication-with-settings-yaml ?

`client_id` and `client_secret`? 

or actual Auth tokens (credentials file)?

**Comment by leiyiz** [comment]
Thanks for the fast reply!
I meant the actual OAuth token

**Comment by shcheklein** [comment]
@leiyiz yeah, I'm not aware about this, unfortunately. What is your use case, may be I can help you with a workaround?

**Comment by leiyiz** [comment]
Thanks! Basically I want to either limit the access scope for the OAuth token or to encrypt the OAuth token that I saved. Maybe there's an argument that I don't have to? but I think right now that saving it in plain text is not that safe.

**Comment by shcheklein** [comment]
@leiyiz access scope is defined by the application (`client_id/client_secret`) unless I'm missing something. 

Good point about encrypting it. I'm not sure if it's that much safer - you will have a key in your code to decrypt it? But I'm not an expert in this and not that much I can recommend. The only options is to read an encrypted file in the code, write it to temporary unencrypted and delete it after the process is done. But it's clearly doesn't make that much better.

**Comment by leiyiz** [comment]
Right, thanks!
