### ISSUE TITLE
[QUESTION] show upload/download loading?

### ISSUE THREAD

**Issue by LeonardoRick** [iterative/PyDrive2#98]
Is there a way to show the percentage of upload/download fo large files?

**Comment by efiop** [comment]
Hi @LeonardoRick .

For downloading, you could use `callack` arg https://github.com/iterative/dvc/blob/47bcb02ef1749d057889c643631a205cdbf004b9/dvc/fs/gdrive.py#L372 and for uploading you'll need to wrap the fobj you are passing (e.g. with https://tqdm.github.io/docs/tqdm/#wrapattr).

**Comment by LeonardoRick** [comment]
Hi @efiop thanks for answering. I was struggling to understand how to use those two libraries together but its being hard for me. Could you give me some light. Today, this is my `uploadFile` function. How can I use wrapattr with that?

```python
    # upload file and return instance
    def uploadFile(self, filepath: str, filename: str, parent_id: str) -> GoogleDriveFile:
        f = self.drive.CreateFile({'parents': [{'id': parent_id}]})
        f.SetContentFile(filepath)
        f['title'] = filename
        f.Upload()
        return f
```
