### ISSUE TITLE
LocalWebserverAuth: KeyError: '_module'

### ISSUE THREAD

**Issue by hagemouse** [iterative/PyDrive2#99]
It was working well yesterday. But today, following error occurred. Nothing changed.    

```python
 googlefile.FetchMetadata(fetch_all= True)
  File "/home/km/.local/share/lib/python3.8/site-packages/pydrive2/auth.py", line 60, in _decorated
    self.auth.LocalWebserverAuth()
  File "/home/km/.local/share/lib/python3.8/site-packages/pydrive2/auth.py", line 121, in _decorated
    self.LoadCredentials()
  File "/home/km/.local/share/lib/python3.8/site-packages/pydrive2/auth.py", line 327, in LoadCredentials
    self.LoadCredentialsFile()
  File "/home/km/.local/share/lib/python3.8/site-packages/pydrive2/auth.py", line 348, in LoadCredentialsFile
    self.credentials = storage.get()
  File "/home/km/.local/share/lib/python3.8/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/home/km/.local/share/lib/python3.8/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/home/km/.local/share/lib/python3.8/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

Is there anything changed in Google?
Thank you.

**Comment by hagemouse** [comment]
verision 1.8.1

**Comment by shcheklein** [comment]
@hagemouse what version fails? 1.8.1? how do you do auth?

**Comment by hagemouse** [comment]
1. get client_secrets.json 

2. settings.yaml
client_config_backend: settings
client_config:
  client_id: 8539k0h.apps.googleusercontent.com
  client_secret: MDP_4nh1d7

save_credentials: True
save_credentials_backend: file
save_credentials_file: client_secrets.json
get_refresh_token: True

3.run:
 gauth = GoogleAuth()
 drive = GoogleDrive(gauth)
f = drive.CreateFile({"id": folder_id})
f.FetchMetadata(fetch_all= True)   ---->error here

Both 1.8.1 and 1.7.2

**Comment by shcheklein** [comment]
@hagemouse `save_credentials_file: client_secrets.json` this line breaks it. `client_secrets.json` is a file that contains `client_id` and `client_secret` for you. Since you specify them directly in the `client_config` field in the `settings.yaml` you don't need this file anymore.

Now, `save_credentials_file` is not about `secret/id` - it's about those tokens that Google Drive API returns after the initial Auth. Usually you want to save it in a separate file. In you case you pointed PyDrive2 to the `client_secrets.json`, and it was trying to read it in the same way as it would read the actual credentials file, while it is not. That's why you are getting this error.

To fix this you can do something like:

`save_credentials_file: gdrive-credentials.json`

**Comment by hagemouse** [comment]
I see. And it works well now.
Thank you very much.

**Comment by abubelinha** [comment]
Thanks @shcheklein , I was having this issue too when trying to modify a previous script to use settings.yaml 
But one question remains: Why the error raised if "nothing changed"?
> It was working well yesterday. But today, following error occurred. Nothing changed.

In my case, I was not using settings.yaml but a different approach which worked for several years:
```Python
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
gauth = GoogleAuth()

credsfile = 'mycreds.txt'

# Try to load saved client credentials
gauth.LoadCredentialsFile(credsFile)
if gauth.credentials is None:
    # Authenticate if they're not there
    gauth.LocalWebserverAuth()
elif gauth.access_token_expired:
    # Refresh them if expired
    gauth.Refresh()
else:
    # Initialize the saved creds
    gauth.Authorize()
# Save the current credentials to a file
gauth.SaveCredentialsFile(credsFile)
```

For some reason this stopped working (as it used to happen once a year, but I used to solve it deleting credentials file, which was regenerated when running my script again and being prompted to authorize it again in a web interface). 

But today I was not being able to solve it.
So I gave up and tried the settings.yaml approach, which worked.  But I still have some questions:

1. Is the `save_credentials_file` settings.yaml directive equivalent to `gauth.SaveCredentialsFile()` in my old script?
2. Will settings.yaml also stop working from time to time? (as @hagemouse mentioned "this was working and suddenly it does not work anymore") 
3. Is there any settings.yaml switch we can use to prevent that, so our scripts can run unattended forever?

Thanks!
